import type { IndexEntry } from "./index";
import { latestRunSummariesFromIndex } from "./index";

const START = "<!-- compat-summary:start -->";
const END = "<!-- compat-summary:end -->";

export function renderReadmeCompatSummary(index: { runs: IndexEntry[] }): string {
  const latest = latestRunSummariesFromIndex(index);
  const newest = index.runs[0]?.finishedAt ?? "unknown";
  const lines = [
    START,
    "",
    "_Generated by `bun run testsuite --update-summaries` from the latest committed reports._",
    "",
    `Last updated: ${newest}`,
    "",
    "![Latest compatibility pass rates](reports/pass-rate.svg)",
    "",
    "| Suite | Version | Digest | Pass rate | Regressions |",
    "|---|---|---|---:|---:|",
  ];
  for (const run of latest) {
    lines.push(
      `| ${run.workload} | \`${run.semver}\` | \`${run.digest}\` | ${(run.passRate * 100).toFixed(1)}% | ${run.regressions} |`,
    );
  }
  lines.push("", END, "");
  return lines.join("\n");
}

export async function updateReadmeCompatSummary(readmePath: string, index: { runs: IndexEntry[] }): Promise<void> {
  const current = await Bun.file(readmePath).text();
  const replacement = renderReadmeCompatSummary(index);
  const start = current.indexOf(START);
  const end = current.indexOf(END);
  let base = current;
  if (start >= 0 && end > start) {
    const headingStart = current.lastIndexOf("## Latest compatibility", start);
    const removeStart = headingStart >= 0 ? headingStart : start;
    base = `${current.slice(0, removeStart)}${current.slice(end + END.length)}`;
  }

  const section = `## Latest compatibility\n\n${replacement}`;
  const howItWorks = base.indexOf("## How it works");
  if (howItWorks >= 0) {
    const prefix = base.slice(0, howItWorks).trimEnd();
    const suffix = base.slice(howItWorks).trimStart();
    await Bun.write(readmePath, `${prefix}\n\n${section}\n${suffix.endsWith("\n") ? suffix : `${suffix}\n`}`);
    return;
  }

  const suffix = base.endsWith("\n") ? "" : "\n";
  await Bun.write(readmePath, `${base}${suffix}\n${section}`);
}
