import type { IndexEntry } from "./index";
import { latestRunSummariesFromIndex } from "./index";

const START = "<!-- compat-summary:start -->";
const END = "<!-- compat-summary:end -->";

export function renderReadmeCompatSummary(index: { runs: IndexEntry[] }): string {
  const latest = latestRunSummariesFromIndex(index);
  const newest = index.runs[0]?.finishedAt ?? "unknown";
  const lines = [
    START,
    "",
    "_Generated by `./bin/run --update-summaries` from the latest committed reports._",
    "",
    `Last updated: ${newest}`,
    "",
    "![Latest compatibility pass rates](reports/pass-rate.svg)",
    "",
    "| Suite | Version | Digest | Pass rate | Regressions |",
    "|---|---|---|---:|---:|",
  ];
  for (const run of latest) {
    lines.push(
      `| ${run.workload} | \`${run.semver}\` | \`${run.digest}\` | ${(run.passRate * 100).toFixed(1)}% | ${run.regressions} |`,
    );
  }
  lines.push("", END, "");
  return lines.join("\n");
}

export async function updateReadmeCompatSummary(readmePath: string, index: { runs: IndexEntry[] }): Promise<void> {
  const current = await Bun.file(readmePath).text();
  const replacement = renderReadmeCompatSummary(index);
  const start = current.indexOf(START);
  const end = current.indexOf(END);
  if (start >= 0 && end > start) {
    const next = `${current.slice(0, start)}${replacement}${current.slice(end + END.length)}`;
    await Bun.write(readmePath, next);
    return;
  }
  const suffix = current.endsWith("\n") ? "" : "\n";
  await Bun.write(readmePath, `${current}${suffix}\n## Latest compatibility\n\n${replacement}`);
}
