import { join, resolve } from "node:path";
import { mkdirSync } from "node:fs";
import { loadRegistry } from "./registry";
import { resolveIdentity } from "./elide";
import { loadExpectations, skipGlobs } from "./expectations/load";
import { compare } from "./expectations/compare";
import { ratchetCandidates, writeRatchet, ratchetPath } from "./expectations/ratchet";
import { writeResults, readResults } from "./results/store";
import { diffRuns, renderDiffMd, toRunResults, findPreviousRunDir, loadRunResultsFromDb } from "./analyze/diff";
import { test262Adapter } from "./adapters/test262";
import type { Adapter } from "./adapters/types";
import type { Result, RunMeta, TestResult } from "./results/schema";
import { renderSuiteReport, renderRunIndex } from "./report/render";
import { writeSummaryJson, rebuildTopIndex } from "./report/index";
import { openDb } from "./db/open";
import { resetDb } from "./db/schema";
import { ingestAll } from "./db/ingest";
import { computeImpact, renderImpactMd } from "./analyze/impact";

export interface CliOptions {
  command: string;
  workload: string;
  elidePath: string;
  digest: string;
  suiteRoot: string;
  reportsDir: string;
  expectationsDir: string;
  threads: number;
  log: boolean;
  include?: string; // comma-separated glob override (else registry settings.include)
  suiteVersion?: string;
  ratchet: boolean;
}

const ADAPTERS: Record<string, Adapter> = { test262: test262Adapter };

export function parseArgs(argv: string[]): CliOptions {
  const [command, workload, ...rest] = argv;
  const get = (flag: string, dflt: string): string => {
    const i = rest.indexOf(flag);
    return i >= 0 ? rest[i + 1] : dflt;
  };
  return {
    command,
    workload,
    elidePath: get("--elide-path", "/opt/elide/bin/elide"),
    digest: get("--digest", "local"),
    suiteRoot: get("--suite-root", resolve("suites")),
    reportsDir: get("--reports", resolve("reports")),
    expectationsDir: get("--expectations", resolve("expectations")),
    threads: parseInt(get("--threads", "1"), 10),
    log: rest.includes("--log"),
    include: get("--include", "") || undefined,
    suiteVersion: get("--suite-version", "") || undefined,
    ratchet: rest.includes("--ratchet"),
  };
}

const DB_PATH = resolve(".harness/results.sqlite");

export async function dbBuild(reportsDir = resolve("reports")): Promise<number> {
  const db = openDb(DB_PATH);
  resetDb(db);
  const n = await ingestAll(db, reportsDir, { force: true });
  console.log(`db build: ingested ${n} run(s) into ${DB_PATH}`);
  return 0;
}

const MARK: Record<string, string> = {
  pass: "✅",
  fail: "❌",
  error: "🛑",
  skip: "⊘",
};

export async function main(o: CliOptions): Promise<number> {
  const registry = loadRegistry(resolve("registry.toml"));
  const wl = registry.find((w) => w.id === o.workload);
  if (!wl) throw new Error(`unknown workload: ${o.workload}`);
  const adapter = ADAPTERS[wl.adapter];
  if (!adapter) throw new Error(`no adapter for: ${wl.adapter}`);

  const identity = await resolveIdentity(o.elidePath, o.digest);
  const exp = loadExpectations(join(o.expectationsDir, `${wl.id}.toml`));
  const startedAt = new Date().toISOString();

  const ctx = {
    elide: identity,
    elidePath: o.elidePath,
    suitePath: join(o.suiteRoot, wl.id.replace(/^.*\//, "")),
    include: o.include
      ? o.include.split(",").map((s) => s.trim()).filter(Boolean)
      : (wl.settings.include as string[]) ?? ["test/**/*.js"],
    skipGlobs: skipGlobs(exp),
    threads: o.threads,
  };

  const results: Result[] = [];
  for await (const r of adapter.run(ctx)) {
    results.push(r);
    if (o.log && r.kind === "test") {
      // Live per-test marks go to stderr so stdout stays clean for the summary.
      const tail = r.status === "fail" || r.status === "error" ? `  — ${r.message ?? ""}` : "";
      process.stderr.write(`${MARK[r.status] ?? "?"} ${r.id}${tail}\n`);
    }
  }
  const finishedAt = new Date().toISOString();

  const tests = results.filter((r): r is TestResult => r.kind === "test");
  const cmp = compare(tests, exp);
  let comparison = cmp;
  if (o.ratchet) {
    const ids = ratchetCandidates(tests, exp);
    const header =
      `# AUTO-GENERATED by \`run --ratchet\`. Do not edit by hand.\n` +
      `# Generated for elide ${identity.semver} (sha ${identity.digest.slice(0, 12)}) on ${finishedAt}.`;
    writeRatchet(ratchetPath(o.expectationsDir, wl.id), ids, header);
    for (const id of ids) exp.ratchet.add(id);
    comparison = compare(tests, exp); // re-evaluate: ratcheted fails are now expected
  }

  const meta: RunMeta = {
    workload: wl.id,
    kind: wl.kind,
    elide: identity,
    startedAt,
    finishedAt,
    suiteVersion: o.suiteVersion,
  };

  const shortDigest = identity.digest.slice(0, 12) || "local";
  const outDir = join(o.reportsDir, identity.semver, shortDigest);
  mkdirSync(outDir, { recursive: true });
  await writeResults(outDir, meta, results);
  await writeSummaryJson(outDir, meta, comparison);
  await Bun.write(join(outDir, `${wl.id}.md`), renderSuiteReport(meta, comparison));
  await Bun.write(join(outDir, "index.md"), renderRunIndex(meta, comparison));
  await Bun.write(join(o.reportsDir, "index.md"), await rebuildTopIndex(o.reportsDir));

  // Per-version changelog vs the previous run of this workload.
  const prevDir = await findPreviousRunDir(o.reportsDir, wl.id, identity);
  if (prevDir) {
    const prev = toRunResults(await readResults(prevDir));
    const diff = diffRuns(prev, toRunResults({ meta, results }));
    await Bun.write(join(outDir, "changes.json"), JSON.stringify(diff, null, 2));
    await Bun.write(join(outDir, "changes.md"), renderDiffMd(diff));
  }

  // Impact-ordered failure clustering for this run.
  const failRows = tests
    .filter((t) => t.status === "fail" || t.status === "error")
    .map((t) => ({
      id: t.id,
      status: t.status,
      message: t.message,
      features: (t.meta?.features as string[]) ?? [],
    }));
  const impact = computeImpact(failRows);
  await Bun.write(join(outDir, "impact.json"), JSON.stringify(impact, null, 2));
  await Bun.write(join(outDir, "impact.md"), renderImpactMd(impact));

  const green = comparison.regressions.length === 0;
  console.log(
    `${wl.id} @ ${identity.semver}: ${comparison.counts.pass}/${comparison.counts.total} pass, ` +
      `${comparison.regressions.length} regressions, ${comparison.newPasses.length} new passes — ${green ? "GREEN" : "RED"}`,
  );
  return green ? 0 : 1;
}

if (import.meta.main) {
  const argv = Bun.argv.slice(2);
  const command = argv[0];
  let code = 0;
  switch (command) {
    case "run":
      code = await main(parseArgs(argv));
      break;
    case "db":
      if (argv[1] !== "build") {
        console.error("usage: cli.ts db build");
        code = 2;
      } else {
        code = await dbBuild();
      }
      break;
    case "diff": {
      const reportsDir = resolve("reports");
      const db = openDb(DB_PATH);
      await ingestAll(db, reportsDir);
      const workload = "test262";
      const rows = db
        .query(`SELECT id, semver, digest FROM runs WHERE workload = ? ORDER BY finished_at DESC`)
        .all(workload) as { id: number; semver: string; digest: string }[];
      const pick = (ref?: string) =>
        ref ? rows.find((r) => r.semver === ref || `${r.semver}/${r.digest}` === ref) : undefined;
      const b = pick(argv[1]) ?? rows[0];
      const a = pick(argv[2]) ?? rows[1];
      if (!a || !b) { console.error("need two runs to diff (run `db build` first)"); code = 2; break; }
      const ra = loadRunResultsFromDb(db, a.id, { semver: a.semver, digest: a.digest });
      const rb = loadRunResultsFromDb(db, b.id, { semver: b.semver, digest: b.digest });
      console.log(renderDiffMd(diffRuns(ra, rb)));
      break;
    }
    case "impact": {
      const db = openDb(DB_PATH);
      await ingestAll(db, resolve("reports"));
      const where = argv[1]
        ? "WHERE workload = 'test262' AND semver = ?" + (argv[2] ? " AND digest LIKE ?||'%'" : "")
        : "WHERE workload = 'test262'";
      const params = argv[1] ? (argv[2] ? [argv[1], argv[2]] : [argv[1]]) : [];
      const run = db
        .query(`SELECT id FROM runs ${where} ORDER BY finished_at DESC LIMIT 1`)
        .get(...params) as { id: number } | undefined;
      if (!run) { console.error("no matching run (run `db build` first)"); code = 2; break; }
      const rows = db
        .query("SELECT test_id, status, message, features FROM results WHERE run_id = ? AND status IN ('fail','error')")
        .all(run.id) as { test_id: string; status: string; message: string | null; features: string | null }[];
      const failRows = rows.map((r) => ({
        id: r.test_id, status: r.status,
        message: r.message ?? undefined,
        features: r.features ? r.features.split(",") : [],
      }));
      console.log(renderImpactMd(computeImpact(failRows)));
      break;
    }
    default:
      console.error("usage: cli.ts <run|db build|diff|impact|query> …");
      code = 2;
  }
  process.exit(code);
}
